<?php
/**
 * Health Report Script will provide and output of the current health reports
 * generated by the sensor data.
 *
 * function examples
 * healthreport.php?bid=0
 * healthreport.php?sid=0
 *
 * Insert new reports for the health monitor to check
 * healthreport.php?submit=true&teds_id=1&checkcode=1&threshold_value=80&report_code=1&report_results=Test%20Report
 */

include_once('config.php');
include_once('dbfunctions.php');
header('Content-Type: application/json');

if(isset($_GET['bid']))
{
    $conn = OrclConnect();
    $bid = $_GET['bid'];
    $sql = 'SELECT * FROM Health_Report WHERE Health_Report.Bridge_ID = :v_bid';
    $stid = oci_parse($conn, $sql);
    oci_bind_by_name($stid, ':v_bid', $bid);
    oci_execute($stid);
    $rows = array();
    while($r = oci_fetch_assoc($stid)) {
        $rows[] = $r;
    }
    $results = (json_encode($rows, JSON_PRETTY_PRINT));
    echo $results;
    oci_free_statement($stid);
    oci_close($conn);


} elseif(isset($_GET['sid'])) {
    $conn = OrclConnect();
    $sid = $_GET['sid'];
    $sql = 'SELECT * FROM Health_Report WHERE Health_Report.Sensor_ID = :v_sid';
    $stid = oci_parse($conn, $sql);
    oci_bind_by_name($stid, ':v_sid', $sid);
    oci_execute($stid);
    $rows = array();
    while($r = oci_fetch_assoc($stid)) {
        $rows[] = $r;
    }
    $results = (json_encode($rows, JSON_PRETTY_PRINT));
    echo $results;
    oci_free_statement($stid);
    oci_close($conn);


} elseif (isset($_GET['submit']) && isset($_GET['teds_id']) && isset($_GET['checkcode']) && isset($_GET['threshold_value']) && isset($_GET['report_code']) && isset($_GET['report_results'])) {
    $conn = OrclConnect();
    $submit  = $_GET['submit'];
    $teds_id  = $_GET['teds_id'];
    $checkcode = $_GET['checkcode'];
    $threshold_value = $_GET['threshold_value'];
    $report_code  = $_GET['report_code'];
    $report_results  = $_GET['report_results'];

    if ($submit == true) {
        $sql = 'INSERT INTO Sensor_Thresholds VALUES (:teds_id,:checkcode,:threshold_value,:report_code,:report_results)';
        $stid = oci_parse($conn, $sql);
        oci_bind_by_name($stid, ':teds_id', $teds_id);
        oci_bind_by_name($stid, ':checkcode', $checkcode);
        oci_bind_by_name($stid, ':threshold_value', $threshold_value);
        oci_bind_by_name($stid, ':report_code', $report_code);
        oci_bind_by_name($stid, ':report_results', $report_results);
        $r = oci_execute($stid);
        oci_free_statement($stid);
        oci_close($conn);
        if (!$r) {
            //$e = oci_error($stid);
            echo false;
        }
        echo true;
    }
}