DROP TABLE SENSOR_DATA;
DROP TABLE SENSOR_TBL;
DROP TABLE TEDS_TBL;
DROP TABLE PHYSICAL_TYPE;
DROP TABLE BRIDGE_TBL;
DROP VIEW BRIDGE;

DROP FUNCTION INSERT_BRIDGE;
DROP FUNCTION INSERT_DATA;
DROP TYPE LOCATION_TYP;

DROP SEQUENCE BRIDGE_SEQ;
DROP SEQUENCE SENSOR_SEQ;
DROP SEQUENCE TEDS_SEQ;
