--Transducer Type Data
INSERT INTO Transducer_Type VALUES (25,'Accelerometer & Force');
INSERT INTO Transducer_Type VALUES (26,'Charge Amplifier (w/ attached accelerometer)');
INSERT INTO Transducer_Type VALUES (27,'Microphone with built-in preamplifier');
INSERT INTO Transducer_Type VALUES (28,'Microphone Preamplfiers (w/ attached microphone)');
INSERT INTO Transducer_Type VALUES (29,'Microphones (capacitive)');
INSERT INTO Transducer_Type VALUES (30,'High-Level Voltage Output Sensors');
INSERT INTO Transducer_Type VALUES (31,'Current Loop Output Sensors');
INSERT INTO Transducer_Type VALUES (32,'Resistance Sensors');
INSERT INTO Transducer_Type VALUES (33,'Bridge Sensors');
INSERT INTO Transducer_Type VALUES (34,'AC Linear/Rotary Variable Differential Transformer (LVDT/RVDT) Sensors');
INSERT INTO Transducer_Type VALUES (35,'Strain Gage');
INSERT INTO Transducer_Type VALUES (36,'Thermocouple');
INSERT INTO Transducer_Type VALUES (37,'Resistance Temperature Detectors (RTDs)');
INSERT INTO Transducer_Type VALUES (38,'Thermistor');
INSERT INTO Transducer_Type VALUES (39,'Potentiometric Voltage Divider');
INSERT INTO Transducer_Type VALUES (40,'Calibration Table');
INSERT INTO Transducer_Type VALUES (41,'Calibration Curve (Polynomial)');
INSERT INTO Transducer_Type VALUES (42,'Frequency Response Table');
INSERT INTO Transducer_Type VALUES (43,'Charge Amplifier (w/ attached force transducer)');

-- Physical Type Data
INSERT INTO Physical_Type VALUES (0,'K');
INSERT INTO Physical_Type VALUES (1,'°C');
INSERT INTO Physical_Type VALUES (2,'strain');
INSERT INTO Physical_Type VALUES (3,'microstrain');
INSERT INTO Physical_Type VALUES (4,'N');
INSERT INTO Physical_Type VALUES (5,'LB');
INSERT INTO Physical_Type VALUES (6,'kgf');
INSERT INTO Physical_Type VALUES (7,'m/s^2');
INSERT INTO Physical_Type VALUES (8,'ga');
INSERT INTO Physical_Type VALUES (9,'Nm/radian 25');
INSERT INTO Physical_Type VALUES (10,'Nm');
INSERT INTO Physical_Type VALUES (11,'oz-in');
INSERT INTO Physical_Type VALUES (12,'Pa');
INSERT INTO Physical_Type VALUES (13,'psi');
INSERT INTO Physical_Type VALUES (14,'Kg');
INSERT INTO Physical_Type VALUES (15,'G');
INSERT INTO Physical_Type VALUES (16,'m');
INSERT INTO Physical_Type VALUES (17,'mm');
INSERT INTO Physical_Type VALUES (18,'in');
INSERT INTO Physical_Type VALUES (19,'m/s');
INSERT INTO Physical_Type VALUES (20,'mph');
INSERT INTO Physical_Type VALUES (21,'fps');
INSERT INTO Physical_Type VALUES (22,'radians');
INSERT INTO Physical_Type VALUES (23,'degrees');
INSERT INTO Physical_Type VALUES (24,'radian/s');
INSERT INTO Physical_Type VALUES (25,'rpm');
INSERT INTO Physical_Type VALUES (26,'Hz');
INSERT INTO Physical_Type VALUES (27,'g/l');
INSERT INTO Physical_Type VALUES (28,'kg/m^3');
INSERT INTO Physical_Type VALUES (29,'mole/m^3');
INSERT INTO Physical_Type VALUES (30,'mole/l');
INSERT INTO Physical_Type VALUES (31,'m^3/m^3');
INSERT INTO Physical_Type VALUES (32,'l/l');
INSERT INTO Physical_Type VALUES (33,'kg/s');
INSERT INTO Physical_Type VALUES (34,'m^3/s');
INSERT INTO Physical_Type VALUES (35,'m^3/hr');
INSERT INTO Physical_Type VALUES (36,'gpm');
INSERT INTO Physical_Type VALUES (37,'cfm');
INSERT INTO Physical_Type VALUES (38,'1/min');
INSERT INTO Physical_Type VALUES (39,'RH');
INSERT INTO Physical_Type VALUES (40,'%');
INSERT INTO Physical_Type VALUES (41,'V');
INSERT INTO Physical_Type VALUES (42,'V rms');
INSERT INTO Physical_Type VALUES (43,'Amperes');
INSERT INTO Physical_Type VALUES (44,'Amperes rms');
INSERT INTO Physical_Type VALUES (45,'Watts');
